language: python
sudo: required
cache:
  directories:
  - $HOME/.cache/pip
install: pip install --upgrade pip tox wheel
script: tox
env:
  - TOXENV=py27-django-19
  - TOXENV=py34-django-19
  - TOXENV=py35-django-19
  - TOXENV=py27-django-110
  - TOXENV=py34-django-110
  - TOXENV=py35-django-110
  - TOXENV=py27-django-111
  - TOXENV=py34-django-111
  - TOXENV=py35-django-111
  - TOXENV=coveralls
